# Generated by Django 5.2 on 2026-02-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('TRADER', 'Trader'), ('ADMIN', 'Admin'), ('MARKET_MAKER', 'Market Maker')], default='TRADER', max_length=20),
        ),
    ]
