# Generated by Django 5.2 on 2026-02-09 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('role', models.CharField(choices=[('TRADER', 'Trader'), ('MARKET_MAKER', 'Market Maker')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='user_role',
            field=models.CharField(choices=[('TRADER', 'Trader'), ('MARKET_MAKER', 'Market Maker')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MarketMaker',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trading.baseuser')),
            ],
            bases=('trading.baseuser',),
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trading.baseuser')),
            ],
            bases=('trading.baseuser',),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.baseuser'),
        ),
        migrations.AlterField(
            model_name='stoploss_order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.baseuser'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_trades', to='trading.baseuser'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_trades', to='trading.baseuser'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
