# Generated by Django 5.2 on 2026-02-10 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_baseuser_order_user_role_marketmaker_trader_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_role',
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.user'),
        ),
        migrations.AlterField(
            model_name='stoploss_order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.user'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_trades', to='trading.user'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_trades', to='trading.user'),
        ),
        migrations.DeleteModel(
            name='MarketMaker',
        ),
        migrations.DeleteModel(
            name='Trader',
        ),
        migrations.DeleteModel(
            name='BaseUser',
        ),
    ]
