# Generated by Django 5.2 on 2026-02-10 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_order_user_role_nullable_backfill'),
    ]

    operations = []
