# Generated by Django 5.2 on 2026-02-10 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_baseuser_marketmaker_trader_alter_order_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
