# Generated by Django 5.2 on 2026-02-10 23:30

from django.db import migrations, models


def backfill_order_user_role(apps, schema_editor):
    Order = apps.get_model('trading', 'Order')
    BaseUser = apps.get_model('trading', 'BaseUser')

    for order in Order.objects.filter(user_role__isnull=True):
        role = None
        if order.user_id:
            try:
                role = BaseUser.objects.get(id=order.user_id).role
            except BaseUser.DoesNotExist:
                role = None

        if role not in ('TRADER', 'MARKET_MAKER'):
            role = 'TRADER'

        order.user_role = role
        order.save(update_fields=['user_role'])


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='role',
            field=models.CharField(choices=[('TRADER', 'Trader'), ('MARKET_MAKER', 'Market Maker'), ('ADMIN', 'Admin')], max_length=20),
        ),
        migrations.RunPython(backfill_order_user_role, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='user_role',
            field=models.CharField(choices=[('TRADER', 'Trader'), ('MARKET_MAKER', 'Market Maker')], max_length=30),
        ),
    ]
